### ISSUE TITLE
FindById Methoden für Airline und City/Market

### ISSUE THREAD

**Issue by Arne2** [ORFAP/FAPBackend#12]
Damit der Crawler die Airlines und Cities mit der Id finden kann, werden findBy Methoden benötigt. Diese bitte bereitstellen...

**Comment by FabianWilms** [comment]
1. Gibt es schon `findAll(id)` und `findOne(id)` durch das CrudRepository
2. wofür braucht der crawler das? Oo

**Comment by Arne2** [comment]
1. Es geht nicht um die Id, die im Link steht, sondern die Variable Id in der Klasse Airline bzw. City.
   Die findOne benutzt die, die im Link steht. Die findById soll nach der Objektvariablen suchen.
2. Wir müssen uns die Id der Links holen können, damit wir die Ruten speichern können. Wir bekommen im zip mit dem POST die Id(Objektvariable) der Airline/Cities.

**Comment by peter-mueller** [comment]
Warum gibt es dann 2x eine ID? Sollte eine (die Objektvariable) nicht reichen?

**Comment by Arne2** [comment]
Es gibt nicht 2x eine Id in der Entität. Die Id, die man mit findOne verwendet nutzt den hintersten Abschnitt von dem selfLink. Die Id der Entität ist die, nach der ich suchen möchte.

**Comment by FabianWilms** [comment]
Ach ihr habt die Entitäten so gemacht. Ich hätte einfach für Airline und City das ID-Feld halt als `@Id` markiert und einfach nicht von BaseEntity abgeleitet. Finde ich so etwas umständlich weil die CrudRepositories das eigentlich alles so handlen könnten. Vor allem könntet ihr dann einfach direkt die Routen erstellen mit der ID die ihr schon von Transtats habt ohne euch erst die vom Backend holen zu müssen.

**Comment by FabianWilms** [comment]
Also im Prinzip genau das wofür rene gerade nen PR aufgemacht hat xD https://github.com/ORFAP/FAPBackend/pull/14/files

**Comment by Arne2** [comment]
Achso wenn er jetzt die Id, die er bekommt hernimmt um den Selflink zu erstellen würde es passen

**Comment by FabianWilms** [comment]
Ignoriert doch mal den selflink xD

**Comment by Arne2** [comment]
Den muss ich aber übergeben, wenn ich das Objekt erstellen will

**Comment by darenegade** [comment]
Auf Wunsch von Arne und Otto heißt es übrigens nicht mehr City sondern Market. 
Wenn @FabianHoltkoetter oder @peter-mueller ein Problem damit haben, dann warte ich noch mit dem merge

**Comment by FabianWilms** [comment]
No problems muss sowieso noch die filter-felder anpassen

**Comment by Arne2** [comment]
Ok funktioniert jetzt, dadurch, dass die Id, die ist, die im Selflink ist. Findby Methode nicht länger von nöten.
