### ISSUE TITLE
Anpassungen Settings-Entity an neue Anforderungen

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAPBackend#9]
Zunächst mal endlich der Enum für die Qualitativen und Quantitativen Werten:

```
QualitiativeValue (X-Axis)
TIME, DESTINATION, AIRLINE
```

```
QuantitiveValue (Y-Axis)
FLIGHTS, PASSENGERS, DELAYFREQ, CANCELLATIONS, AVGDELAY
```

und die Filters-Klasse sieht jetzt auch ein wenig anders aus. Es gibt Filter (oder selektoren) für jeden qualitativen wert.
Außerdem wird noch eine Time-Range benötigt, um anzugeben in welchem Zeitraum die Daten gesammelt werden sollen, sowie ein weiterer Enum-Wert für die Darstellung der Zeit:

```
TimeSteps
DAY_OF_WEEK, MONTH, YEAR
```

Somit würde die Settings-Entität in JSON (beispielhaft) so aussehen:

``` json
name: "Name",
creator: "Ersteller",
shareable: false,
rangeFrom: 2014,
rangeTo: 2016,
axis: {
    x: "TIME",
    y: "FLIGHTS"
},
filter: {
    timeStep: "MONTH",
    destination: [],
    airline: [ ]
}

```

Sollte (insbesondere bei den Enums) was fehlen, bitte korrigieren. Die Feld-Namen sind auch nur zur veranschaulichung :P

**Comment by darenegade** [comment]
☕ ❗ ❗

**Comment by darenegade** [comment]
@FabianHoltkoetter Wie hast du dir das mit der time Liste im Filter gedacht? Ich habe ja momentan ein Date/RangeFrom und Date/RangeTo. Ist das nicht so sinnvoller? In einer Liste könntest du auch mehr als 2 Werte eingeben, was keinen Sinn macht.

**Comment by darenegade** [comment]
Hab gerade gesehen, dass im Setting auch eine Range drin ist. Brauchen wir dann time noch im Filter?

**Comment by FabianWilms** [comment]
Ups! Hast recht, im Filter sollte es keine Liste sein.
Ja der Unterschied ist blöd. Du gibst halt für das Setting an welcher Zeitraum betrachtet werden soll. Also deine Date/RangeFrom und Date/RangeTo.
Das time im Filter soll ein Wert aus dem `TimeSteps`-Enum sein.

**Comment by darenegade** [comment]
TimeSteps hast du aber auch im Setting.

**Comment by FabianWilms** [comment]
Guter Hinweis, der war da falsch xD

**Comment by darenegade** [comment]
Okay, alles klar
